import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      // Generated by `next build`; gitignored, and not ours to lint.
      '**/next-env.d.ts',
      '**/dist/**',
      '**/generated/**',
      'spike/**',
      'design/**',
      'packages/db/prisma/migrations/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.node, ...globals.es2022 },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always'],
    },
  },

  // Web app: browser globals and React hook rules.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: reactHooks.configs.recommended.rules,
  },

  // Scripts and seeds are allowed to talk to the operator.
  {
    files: [
      'scripts/**/*.mjs',
      'packages/db/src/seed.ts',
      'apps/renderer/src/**/*.ts',
      // Route handlers are where structured server logs are written.
      'apps/web/src/app/api/**/*.ts',
    ],
    rules: { 'no-console': 'off' },
  },

  prettier,
);
